packages:
  - "apps/*"
  - "packages/*"

overrides:
  "app-builder-lib>@electron/get": "3.1.0"

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': false
  '@sentry/cli': true
  '@oomol-lab/open-connector@https://codeload.github.com/oomol-lab/open-connector/tar.gz/5719a69468c698c7cb8108e062ff64ecef8a2e65': false
  '@tencentdb-agent-memory/memory-tencentdb-v2@git+https://github.com/NxcoreAI/TencentDB-Agent-Memory.git#f65f83e550cc4a13d51cbef8550f0b1755073ea4&path:MemoryCore': false
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@earendil-works/pi-agent-core@0.84.2'
  - '@earendil-works/pi-ai@0.84.2'
  - '@earendil-works/pi-client@0.84.2'
  - '@earendil-works/pi-coding-agent@0.84.2'
  - '@earendil-works/pi-protocol@0.84.2'
  - '@earendil-works/pi-telemetry@0.84.2'
  - '@earendil-works/pi-tui@0.84.2'
