packages:
  - "apps/*"
  - "packages/*"

overrides:
  "app-builder-lib>@electron/get": "3.1.0"

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': false
  '@sentry/cli': true
  '@tencentdb-agent-memory/memory-tencentdb-v2@git+https://github.com/NxcoreAI/TencentDB-Agent-Memory.git#1d6922225d1ef855371b87ad2c97f1e6dc27ac2d&path:MemoryCore': false
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@earendil-works/pi-agent-core@0.84.2'
  - '@earendil-works/pi-ai@0.84.2'
  - '@earendil-works/pi-client@0.84.2'
  - '@earendil-works/pi-coding-agent@0.84.2'
  - '@earendil-works/pi-protocol@0.84.2'
  - '@earendil-works/pi-telemetry@0.84.2'
  - '@earendil-works/pi-tui@0.84.2'
