CREATE TABLE `reality_events` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`status` text NOT NULL,
	`processing_state` text NOT NULL,
	`capture_device` text NOT NULL,
	`processing_device` text NOT NULL,
	`audio_source` text NOT NULL,
	`audio_file_name` text,
	`audio_mime_type` text,
	`duration_ms` integer DEFAULT 0 NOT NULL,
	`current_topic` text,
	`transcript` text DEFAULT '' NOT NULL,
	`transcript_segments` text NOT NULL,
	`transcript_edited_at` integer,
	`insights` text NOT NULL,
	`markers` text NOT NULL,
	`important` integer DEFAULT false NOT NULL,
	`asr_job_id` text,
	`asr_source` text,
	`result_version` integer DEFAULT 0 NOT NULL,
	`error` text,
	`version` integer DEFAULT 1 NOT NULL,
	`started_at` integer NOT NULL,
	`ended_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `reality_events_asr_job_idx` ON `reality_events` (`asr_job_id`);