import type { ContextRoomRecommendation, ContextRoomRecord } from './types';

const cloudWorkspaceId = '5fc9205a-8077-4e39-bf77-aa5ae6262b93';

export const CONTEXT_ROOMS: ContextRoomRecord[] = [
  {
    id: 'room-launch',
    title: 'NexOS PC 端 V1 发布计划',
    kind: '项目',
    icon: '🚀',
    tone: 'sky',
    status: '进行中',
    starred: true,
    lastViewed: '12 分钟前',
    roomCode: 'V1-LAUNCH',
    recentSource: { type: '会议', name: '客户沟通会' },
    crossHint: '关联 4 人 · 3 项风险 · 2 条待确认记忆',
    brief: {
      background:
        'NexOS PC 端 V1 面向内容创作者与知识工作者，验证「个人上下文中枢」核心闭环。当前进入发布前冲刺。',
      goal: '7 月 30 日完成 V1 内测包，跑通「接入资料 → Room → Agent 生成 → 来源可追溯」主线。',
      status: 'PRD 定稿、原型 V2 完成、开发进入 M2；待确认高风险动作 4 项。',
      risks: ['Gmail 连接器授权即将过期', '会议纪要服务同步延迟', '记忆候选中 2 条重要性待确认'],
      decisions: ['顶部不再设独立菜单栏，统一到标签栏', '右侧智能区改为主动发现提醒栏 + 三态'],
    },
    stats: { docs: 12, mails: 28, meetings: 6, events: 9, memories: 14, tasks: 5 },
    riskCount: 3,
    pendingMemoryCount: 2,
    people: [
      { name: '林薇', role: '设计负责人', avatar: '林' },
      { name: '周明', role: '前端开发', avatar: '周' },
      { name: '苏晗', role: '运营', avatar: '苏' },
      { name: '客户·张总', role: '外部', avatar: '张' },
    ],
    timeline: [
      {
        time: '今天 11:20',
        title: 'Doc Agent 生成《发布方案 V0.2》',
        description: '基于本 Room 12 篇资料生成，已写入并提取 1 条记忆候选',
        kind: 'done',
      },
      {
        time: '今天 09:45',
        title: '客户沟通会纪要写回',
        description: '会议结论已写回《发布方案》，来源保留',
        kind: 'done',
      },
      {
        time: '昨天 18:30',
        title: 'Gmail 授权即将过期',
        description: '连接器状态变更，建议尽快重新授权',
        kind: 'warn',
      },
      {
        time: '昨天 15:10',
        title: '新增 3 篇竞品分析资料',
        description: '来源：邮件附件 + 本地文件夹',
        kind: 'done',
      },
      { time: '07-09', title: '客户沟通会', description: '确认报价区间、交付节奏', kind: 'done' },
    ],
    materials: [
      {
        id: 'doc-plan',
        type: '文档',
        title: 'NexOS PC 端发布方案',
        time: '12 分钟前',
        summary: '该文档与最新邮件存在结论冲突，建议基于客户沟通会结论更新。',
        version: 'V0.2',
        status: 'AI 处理过',
        sourceState: '来源需复核',
      },
      {
        id: 'doc-prd',
        type: '文档',
        title: 'Everroom PC 端 PRD（摘要）',
        time: '昨天',
        summary: '记录本 Room 发布目标与核心场景，是 Agent 生成方案的主要依据。',
        version: 'V1.0',
        status: '已发布',
        sourceState: '来源完整',
      },
      {
        id: 'doc-competitive',
        type: '文档',
        title: '竞品分析：上下文中枢赛道',
        time: '2 天前',
        summary: '记录本 Room 发布目标与核心场景，是 Agent 生成方案的主要依据。',
        version: 'V0.8',
        status: '编辑中',
        sourceState: '来源完整',
      },
      {
        id: 'mail-quote',
        type: '邮件',
        title: '关于 NexOS PC 端报价确认',
        time: '10:42',
        summary: '客户希望本周五（07-14）前确认正式报价区间 ¥45-50w，并附上 V1 方案概要。',
        folder: 'inbox',
        starred: true,
        unread: true,
        sender: '张总 · 星港科技',
        recipient: '我',
        attachments: [{ name: 'NexOS-V1-报价范围.pdf', size: '1.2 MB' }],
        body: '陆远你好，请确认最终报价是否包含部署与首月支持，并在本周五前补充正式报价函和 V1 方案概要。',
        replyDraft: '已收到，正式报价函将包含部署与首月支持范围，并于本周五前发送。',
      },
      {
        id: 'mail-source',
        type: '邮件',
        title: '补充：来源必须可追溯',
        time: '昨天',
        summary: '客户重申 AI 输出需可追溯至具体资料，建议在方案中明确说明。',
        folder: 'inbox',
        unread: true,
        sender: '张总 · 星港科技',
        recipient: '我',
        body: '请在下一版方案中明确所有 AI 结论如何回溯到原始邮件、会议纪要和文件。',
      },
      {
        id: 'mtg-client',
        type: '会议',
        title: '客户沟通会 · 张总',
        time: '07-09 14:00',
        summary: '确认报价区间与交付节奏，客户强调来源可追溯；结论已写回发布方案。',
        attendees: ['张总', '陆远', '林薇'],
        duration: '48 分钟',
        location: '腾讯会议',
        meetingActions: [
          { id: 'mtg-action-quote', title: '补充正式报价函和交付范围', owner: '林薇' },
          { id: 'mtg-action-trace', title: '整理来源可追溯说明', owner: '周明' },
        ],
        transcript: [
          {
            time: '14:03',
            speaker: '张总',
            text: '报价需要覆盖部署和首月支持，交付范围要写清楚。',
          },
          { time: '14:18', speaker: '陆远', text: '下一版方案会补齐来源追溯入口和验收说明。' },
          { time: '14:36', speaker: '林薇', text: '周五前完成正式报价函与方案概要。' },
        ],
      },
    ],
    actionItems: [
      {
        id: 't1',
        title: '出具正式报价函（张总）',
        status: '候选',
        owner: '待确认',
        deadline: '07-14',
        source: { type: '会议', name: '客户沟通会 · 张总', objectId: 'mtg-client' },
      },
      {
        id: 't2',
        title: '准备发布材料初稿',
        status: '进行中',
        owner: '林薇',
        deadline: '07-25',
        source: { type: 'Room', name: 'NexOS PC 端 V1 发布计划' },
      },
      {
        id: 't3',
        title: '整理「来源可追溯」说明',
        status: '未开始',
        owner: '周明',
        deadline: '07-22',
        source: { type: '邮件', name: '补充：来源必须可追溯', objectId: 'mail-source' },
      },
      {
        id: 't4',
        title: '完成 V1 内测包',
        status: '进行中',
        owner: '陆远',
        deadline: '07-30',
        source: { type: 'Room', name: 'NexOS PC 端 V1 发布计划' },
      },
    ],
    graphEdges: [
      { from: '张总', to: '客户沟通会', relation: '人物 · 事件（参与人）' },
      { from: '客户沟通会', to: '报价邮件', relation: '事件 · 事件（触发）' },
      { from: '客户沟通会', to: '发布方案', relation: '事件 · 数据（写回）' },
      { from: '林薇', to: '评审稿.fig', relation: '人物 · 数据（提交）' },
    ],
    pendingMemoryItems: [
      {
        id: 'm1',
        content: '张总对「来源可追溯」非常敏感，所有 AI 输出必须可点开原始资料。',
        type: '人物偏好',
      },
      {
        id: 'm2',
        content: 'NexOS PC 端 V1 报价区间为 ¥45-50w，分两期交付。',
        type: '项目结论',
      },
    ],
    memoryItems: [
      {
        id: 'memory-traceability',
        content: '张总对「来源可追溯」非常敏感，所有 AI 输出必须可点开原始资料。',
        type: '人物偏好',
        status: '待确认',
        sources: [{ type: '会议', name: '客户沟通会 · 张总' }],
      },
      {
        id: 'memory-price-range',
        content: 'NexOS PC 端 V1 报价区间为 ¥45-50w，分两期交付。',
        type: '项目结论',
        status: '已确认',
        sources: [{ type: '邮件', name: '关于 NexOS PC 端报价确认' }],
      },
    ],
    fileItems: [
      {
        id: 'file-prototype-review',
        name: 'V2-评审稿.fig',
        extension: 'FIG',
        time: '昨天',
        summary: '包含 Context Room、Agent 三态与发布流程的评审画板。',
        size: '18.6 MB',
        source: '本地文件夹 / Design',
        lifecycle: '活跃',
      },
      {
        id: 'file-release-checklist',
        name: 'V1-发布检查清单.xlsx',
        extension: 'XLSX',
        time: '2 天前',
        summary: '内测包、连接器与来源追溯的发布前检查项。',
        size: '246 KB',
        source: '本地文件夹 / Release',
        lifecycle: '活跃',
      },
      {
        id: 'file-release-brief',
        name: 'NexOS-V1-发布说明.docx',
        extension: 'DOCX',
        time: '2 天前',
        summary: 'NexOS V1 发布范围、验收说明与上线准备事项。',
        size: '1.3 MB',
        source: '本地文件夹 / Release',
        lifecycle: '活跃',
      },
      {
        id: 'file-release-review',
        name: 'NexOS-V1-发布评审.pptx',
        extension: 'PPTX',
        time: '3 天前',
        summary: '面向发布评审的目标、关键进展与上线计划。',
        size: '38 KB',
        source: '本地文件夹 / Release',
        lifecycle: '活跃',
      },
      {
        id: 'file-release-confirmation',
        name: 'V1-发布范围确认.pdf',
        extension: 'PDF',
        time: '3 天前',
        summary: 'V1 发布范围、验收条目与签署信息。',
        size: '18 KB',
        source: '本地文件夹 / Release',
        lifecycle: '活跃',
      },
    ],
    nextReverseRecall: '23:14',
    cloudDoc: {
      workspaceId: cloudWorkspaceId,
      docId: '3dccc316-5b91-454e-ba8f-d2fdab182937',
      title: 'NexOS PC 端发布方案',
    },
  },
  {
    id: 'room-nexcore-hub-agent-v2',
    title: 'Everroom HUB AI Agent V2',
    kind: '项目',
    icon: 'AI',
    tone: 'sky',
    status: '进行中',
    starred: true,
    lastViewed: '8 分钟前',
    roomCode: 'HUB-AGENT-V2',
    recentSource: { type: '会议', name: 'Agent V2 交互评审' },
    crossHint: '关联 4 人 · 2 项风险 · 2 条待确认记忆',
    brief: {
      background: 'Everroom HUB AI Agent V2 产品研发项目。',
      goal: '完成多 Agent 协同、工具调用与上下文记忆闭环。',
      status: '核心流程联调中，桌面端交互进入评审。',
      risks: ['工具权限边界待确认', '长任务恢复链路尚未压测'],
      decisions: ['采用统一任务时间线', '高风险操作必须二次确认'],
    },
    stats: { docs: 9, mails: 12, meetings: 4, events: 7, memories: 11, tasks: 6 },
    riskCount: 2,
    pendingMemoryCount: 2,
    people: [
      { name: '陆远', role: '产品负责人', avatar: '陆' },
      { name: '林薇', role: '交互设计', avatar: '林' },
      { name: '周明', role: '桌面端开发', avatar: '周' },
      { name: '陈序', role: 'Agent 工程', avatar: '陈' },
    ],
    timeline: [
      {
        time: '今天 16:20',
        title: 'Agent V2 交互评审完成',
        description: '确认任务时间线与权限确认流程。',
        kind: 'done',
      },
      {
        time: '今天 11:40',
        title: '工具调用链路联调',
        description: '文件、邮件与日历工具已接入。',
        kind: 'done',
      },
      {
        time: '昨天 18:10',
        title: '长任务恢复测试',
        description: '发现窗口重启后的状态恢复缺口。',
        kind: 'warn',
      },
      {
        time: '07-22',
        title: 'V2 架构方案定稿',
        description: '确定编排器、工具层与记忆层边界。',
        kind: 'done',
      },
    ],
    materials: [
      {
        id: 'hub-doc-prd-v2',
        type: '文档',
        title: 'Everroom HUB AI Agent V2 PRD',
        time: '今天 15:30',
        summary: '记录 V2 核心场景、任务模型与验收标准。',
        version: 'V2.1',
        status: '编辑中',
        sourceState: '来源完整',
      },
      {
        id: 'hub-doc-architecture',
        type: '文档',
        title: 'Agent V2 技术架构',
        time: '昨天',
        summary: '编排器、工具层、记忆层与桌面运行时架构。',
        version: 'V1.3',
        status: '已发布',
        sourceState: '来源完整',
      },
      {
        id: 'hub-doc-acceptance',
        type: '文档',
        title: 'Agent V2 验收清单',
        time: '2 天前',
        summary: '覆盖工具调用、权限确认和任务恢复。',
        version: 'V0.9',
        status: 'AI 处理过',
        sourceState: '来源完整',
      },
      {
        id: 'hub-mail-permission',
        type: '邮件',
        title: 'Agent V2 权限策略确认',
        time: '今天 10:18',
        summary: '确认外发、删除和账号授权需要二次确认。',
      },
      {
        id: 'hub-mail-runtime',
        type: '邮件',
        title: '桌面运行时联调反馈',
        time: '昨天 17:45',
        summary: '窗口恢复与后台任务状态需要统一。',
      },
      {
        id: 'hub-meeting-review',
        type: '会议',
        title: 'Agent V2 交互评审',
        time: '今天 16:20',
        summary: '通过主流程，保留两项权限交互调整。',
      },
    ],
    actionItems: [
      {
        id: 'hub-task-tool-permissions',
        title: '完成工具权限矩阵',
        status: '进行中',
        owner: '陈序',
        deadline: '07-26',
      },
      {
        id: 'hub-task-resume',
        title: '修复长任务恢复链路',
        status: '进行中',
        owner: '周明',
        deadline: '07-28',
      },
      {
        id: 'hub-task-prototype',
        title: '更新 Agent V2 交互稿',
        status: '未开始',
        owner: '林薇',
        deadline: '07-27',
      },
      {
        id: 'hub-task-acceptance',
        title: '执行 V2 端到端验收',
        status: '候选',
        owner: '陆远',
        deadline: '07-31',
      },
    ],
    graphEdges: [
      { from: 'Agent V2 交互评审', to: 'V2 PRD', relation: '事件 · 数据（确认）' },
      { from: '陈序', to: '工具权限矩阵', relation: '人物 · 数据（负责）' },
      { from: '长任务恢复测试', to: '桌面运行时', relation: '事件 · 系统（阻塞）' },
      { from: 'Agent V2', to: 'Everroom HUB', relation: '项目 · 产品（归属）' },
    ],
    pendingMemoryItems: [
      {
        id: 'hub-pending-permission',
        content: '外发、删除与账号授权操作必须二次确认。',
        type: '项目结论',
      },
      {
        id: 'hub-pending-resume',
        content: '长任务需要在 Electron 窗口重启后恢复。',
        type: '项目结论',
      },
    ],
    memoryItems: [
      {
        id: 'hub-memory-permission',
        content: '外发、删除与账号授权操作必须二次确认。',
        type: '项目结论',
        status: '待确认',
      },
      {
        id: 'hub-memory-timeline',
        content: '所有 Agent 子任务统一显示在任务时间线。',
        type: '项目结论',
        status: '已确认',
      },
      {
        id: 'hub-memory-response',
        content: 'Agent 回复优先展示结果、状态和来源。',
        type: '表达偏好',
        status: '已确认',
      },
    ],
    fileItems: [
      {
        id: 'hub-file-prototype',
        name: 'Everroom-HUB-Agent-V2.fig',
        extension: 'FIG',
        time: '今天',
        summary: 'Agent V2 桌面端交互与状态页面。',
      },
      {
        id: 'hub-file-permission-matrix',
        name: 'Agent-V2-权限矩阵.xlsx',
        extension: 'XLSX',
        time: '昨天',
        summary: '工具权限等级与确认策略。',
      },
    ],
    nextReverseRecall: '22:30',
    cloudDoc: {
      workspaceId: cloudWorkspaceId,
      docId: '8fd563a7-bf12-4ef7-a40d-bced0b2d615a',
      title: 'Everroom HUB AI Agent V2 PRD',
    },
  },
  {
    id: 'room-zhang',
    title: '客户·张总',
    kind: '人物',
    icon: '👤',
    tone: 'emerald',
    status: '活跃',
    starred: false,
    lastViewed: '昨天',
    roomCode: 'PERSON-ZHANG',
    recentSource: { type: '邮件', name: '补充：来源必须可追溯' },
    crossHint: '关联 1 人 · 1 项风险 · 1 条待确认记忆',
    brief: {
      background: '关键客户决策人，关注交付质量与来源可追溯。',
      goal: '维持长期合作，推进 V1 采购。',
      status: '报价沟通中',
      risks: ['对 AI 生成内容可信度有顾虑'],
      decisions: ['报价区间 ¥45-50w'],
    },
    stats: { docs: 5, mails: 18, meetings: 3, events: 2, memories: 6, tasks: 2 },
    riskCount: 1,
    pendingMemoryCount: 1,
    people: [{ name: '张总', role: '客户决策人', avatar: '张' }],
    timeline: [
      {
        time: '今天 10:42',
        title: '报价邮件上下文更新',
        description: '已关联报价区间、交付节奏与来源可追溯要求',
        kind: 'done',
      },
      {
        time: '昨天',
        title: '反馈邮件：来源必须可追溯',
        description: '强调 AI 输出需可点开具体资料',
        kind: 'warn',
      },
      {
        time: '07-09',
        title: '客户沟通会完成',
        description: '确认采购意向、两期交付方案和正式报价范围',
        kind: 'done',
      },
    ],
    materials: [
      {
        id: 'doc-zhang-profile',
        type: '文档',
        title: '客户沟通与决策偏好',
        time: '今天',
        summary: '汇总张总的决策关注点、报价口径和来源追溯要求。',
        version: 'V0.3',
        status: 'AI 处理过',
        sourceState: '来源完整',
      },
      {
        id: 'mail-source',
        type: '邮件',
        title: '补充：来源必须可追溯',
        time: '昨天',
        summary: '客户重申 AI 输出需可追溯至具体资料，建议在方案中明确说明。',
      },
      {
        id: 'mtg-client',
        type: '会议',
        title: '客户沟通会 · 张总',
        time: '07-09 14:00',
        summary: '确认采购意向、报价区间、交付节奏与来源可追溯要求。',
      },
    ],
    actionItems: [
      {
        id: 't-zhang-trace',
        title: '更新报价与来源追溯说明',
        status: '进行中',
        owner: '林薇',
        deadline: '07-23',
      },
      {
        id: 't-zhang-acceptance',
        title: '确认二期交付验收口径',
        status: '候选',
        owner: '待确认',
        deadline: '07-24',
      },
    ],
    graphEdges: [
      { from: '张总', to: '客户沟通会', relation: '人物 · 事件（参与人）' },
      { from: '张总', to: 'NexOS PC 端 V1', relation: '人物 · 项目（决策人）' },
    ],
    pendingMemoryItems: [
      {
        id: 'm-zhang-acceptance',
        content: '正式报价需要同时列出两期交付范围和验收节点。',
        type: '客户要求',
      },
    ],
    memoryItems: [
      {
        id: 'memory-zhang-evidence',
        content: '张总偏好先查看可追溯依据，再确认 AI 生成结论。',
        type: '人物偏好',
        status: '已确认',
      },
      {
        id: 'memory-zhang-acceptance',
        content: '正式报价需要同时列出两期交付范围和验收节点。',
        type: '客户要求',
        status: '待确认',
      },
    ],
    fileItems: [
      {
        id: 'file-zhang-requirement',
        name: '张总需求确认.pdf',
        extension: 'PDF',
        time: '昨天',
        summary: '客户签字确认的 V1 范围、报价区间与来源追溯要求。',
      },
    ],
    nextReverseRecall: '20:00',
    cloudDoc: {
      workspaceId: cloudWorkspaceId,
      docId: '9a60f944-364a-4126-97df-240cdd486722',
      title: '客户·张总上下文记录',
    },
  },
  {
    id: 'room-pkm',
    title: '个人知识管理',
    kind: '主题',
    icon: '🧠',
    tone: 'amber',
    status: '进行中',
    starred: true,
    lastViewed: '3 天前',
    roomCode: 'TOPIC-PKM',
    recentSource: { type: '文档', name: '我的写作方法论 2026' },
    crossHint: '长期主题持续积累 · 31 条记忆事实',
    brief: {
      background: '长期主题：PKM 方法论与工具实践。',
      goal: '形成可复用的写作与整理方法论。',
      status: '持续积累',
      risks: [],
      decisions: [],
    },
    stats: { docs: 24, mails: 8, meetings: 2, events: 0, memories: 31, tasks: 1 },
    riskCount: 0,
    pendingMemoryCount: 1,
    people: [{ name: '陆远', role: '知识管理实践者', avatar: '陆' }],
    timeline: [
      {
        time: '今天 08:10',
        title: '完成一次反向回忆',
        description: '从 31 条记忆事实中召回 4 条与写作流程相关的结论',
        kind: 'done',
      },
      {
        time: '3 天前',
        title: '更新《我的写作方法论 2026》',
        description: '补充大纲优先和证据卡片的整理步骤',
        kind: 'done',
      },
      {
        time: '上周',
        title: '导入旧笔记存在重复项',
        description: '系统发现 6 条相似记忆，等待合并确认',
        kind: 'warn',
      },
    ],
    materials: [
      {
        id: 'doc-method',
        type: '文档',
        title: '我的写作方法论 2026',
        time: '上周',
        summary: '记录长期写作与知识整理方法，是该主题 Room 的主要依据。',
        version: 'V1.4',
        status: '编辑中',
        sourceState: '来源完整',
      },
      {
        id: 'mail-pkm-digest',
        type: '邮件',
        title: 'PKM 周刊：渐进式总结实践',
        time: '3 天前',
        summary: '整理渐进式总结、反向链接和周期回顾的近期实践。',
      },
    ],
    actionItems: [
      {
        id: 't-pkm-map',
        title: '整理 PARA 与 Room 的映射规则',
        status: '进行中',
        owner: '陆远',
        deadline: '本周',
      },
    ],
    graphEdges: [
      { from: '写作方法论', to: '大纲优先', relation: '文档 · 事实（提取）' },
      { from: '渐进式总结', to: '个人知识管理', relation: '事实 · Room（归属）' },
    ],
    pendingMemoryItems: [
      { id: 'm3', content: '陆远倾向于在方案中先给大纲再展开正文。', type: '表达偏好' },
    ],
    memoryItems: [
      {
        id: 'memory-pkm-outline',
        content: '陆远倾向于先形成结构化大纲，再逐段补充证据和正文。',
        type: '表达偏好',
        status: '待确认',
      },
      {
        id: 'memory-pkm-review',
        content: '每周五执行一次知识库反向回忆与重复记忆清理。',
        type: '工作习惯',
        status: '已确认',
      },
    ],
    fileItems: [
      {
        id: 'file-pkm-map',
        name: 'PKM-信息流地图.png',
        extension: 'PNG',
        time: '上周',
        summary: '展示收集、提炼、连接、输出和复盘五个知识工作阶段。',
      },
    ],
    nextReverseRecall: '明日 08:00',
    cloudDoc: {
      workspaceId: cloudWorkspaceId,
      docId: 'e3000c26-11df-4066-9bdf-cf1877bbff7f',
      title: '我的写作方法论 2026',
    },
  },
  {
    id: 'room-career',
    title: '2026 职业规划',
    kind: '长期目标',
    icon: '🎯',
    tone: 'rose',
    status: '活跃',
    starred: false,
    lastViewed: '上周',
    roomCode: 'GOAL-2026',
    recentSource: { type: '任务', name: 'Q3 职业复盘' },
    crossHint: '年度目标 · 3 项任务 · 下次复盘 09-30',
    brief: {
      background: '年度职业方向与能力建设。',
      goal: '向 AI 产品方向深入。',
      status: 'Q3 复盘中',
      risks: [],
      decisions: [],
    },
    stats: { docs: 6, mails: 3, meetings: 1, events: 4, memories: 9, tasks: 3 },
    riskCount: 0,
    pendingMemoryCount: 1,
    people: [
      { name: '陆远', role: '目标负责人', avatar: '陆' },
      { name: '陈老师', role: '职业导师', avatar: '陈' },
    ],
    timeline: [
      {
        time: '本周一',
        title: 'Q3 职业复盘开始',
        description: '基于项目经历和能力矩阵生成第一版复盘框架',
        kind: 'done',
      },
      {
        time: '上周',
        title: '导师反馈写回 Room',
        description: '建议强化 AI 产品策略与跨团队推进两项能力',
        kind: 'done',
      },
      {
        time: '07-01',
        title: '季度目标存在进度风险',
        description: '作品集案例尚未补齐量化结果和复盘结论',
        kind: 'warn',
      },
    ],
    materials: [
      {
        id: 'doc-career',
        type: '文档',
        title: 'Q3 职业复盘',
        time: '上周',
        summary: '记录年度职业方向、能力建设与 Q3 阶段复盘。',
        version: 'V0.6',
        status: '编辑中',
        sourceState: '来源完整',
      },
      {
        id: 'mail-career-mentor',
        type: '邮件',
        title: 'Q3 职业方向反馈',
        time: '上周',
        summary: '导师建议聚焦 AI 产品策略、复杂项目推进与对外表达。',
      },
    ],
    actionItems: [
      { id: 't5', title: 'Q3 职业复盘', status: '未开始', owner: '陆远', deadline: '09-30' },
      {
        id: 't-career-portfolio',
        title: '补齐作品集量化结果',
        status: '进行中',
        owner: '陆远',
        deadline: '08-15',
      },
      {
        id: 't-career-mentor',
        title: '预约下一次导师沟通',
        status: '候选',
        owner: '待确认',
        deadline: '08-20',
      },
    ],
    graphEdges: [
      { from: '2026 职业规划', to: 'AI 产品策略', relation: 'Room · 目标（聚焦）' },
      { from: '陈老师', to: 'Q3 职业复盘', relation: '人物 · 文档（反馈）' },
    ],
    pendingMemoryItems: [
      {
        id: 'm-career-focus',
        content: '下一阶段优先补强 AI 产品策略与复杂项目推进能力。',
        type: '发展方向',
      },
    ],
    memoryItems: [
      {
        id: 'memory-career-focus',
        content: '下一阶段优先补强 AI 产品策略与复杂项目推进能力。',
        type: '发展方向',
        status: '待确认',
      },
      {
        id: 'memory-career-evidence',
        content: '作品集案例需要同时呈现业务结果、决策依据和个人贡献。',
        type: '复盘结论',
        status: '已确认',
      },
    ],
    fileItems: [
      {
        id: 'file-career-matrix',
        name: 'AI产品能力矩阵.xlsx',
        extension: 'XLSX',
        time: '2 周前',
        summary: '按产品策略、用户研究、交付推进和表达影响力评估当前能力。',
      },
    ],
    nextReverseRecall: '明日 10:20',
    cloudDoc: {
      workspaceId: cloudWorkspaceId,
      docId: '39d11a63-c329-4894-bc80-f9cada0bffca',
      title: 'Q3 职业复盘',
    },
  },
  {
    id: 'room-old',
    title: 'Q1 产品复盘（归档）',
    kind: '项目',
    icon: '📦',
    tone: 'zinc',
    status: '已归档',
    starred: false,
    lastViewed: '3 个月前',
    roomCode: 'Q1-ARCHIVE',
    recentSource: { type: '文档', name: 'Q1 产品复盘' },
    crossHint: '已归档 · 仅保留历史上下文',
    brief: {
      background: '已归档项目。',
      goal: '暂无',
      status: '归档',
      risks: [],
      decisions: [],
    },
    stats: { docs: 8, mails: 4, meetings: 2, events: 3, memories: 3, tasks: 1 },
    riskCount: 0,
    pendingMemoryCount: 0,
    people: [
      { name: '林薇', role: '产品设计', avatar: '林' },
      { name: '周明', role: '前端开发', avatar: '周' },
    ],
    timeline: [
      {
        time: '04-02',
        title: 'Q1 产品复盘归档',
        description: '复盘文档、会议纪要与关键结论转为只读历史上下文',
        kind: 'done',
      },
      {
        time: '03-29',
        title: '复盘会结论写回',
        description: '确认导航改版有效，但首次任务成功率仍需提升',
        kind: 'done',
      },
      {
        time: '03-25',
        title: '汇总 Q1 指标',
        description: '完成激活率、任务完成率和反馈分类统计',
        kind: 'done',
      },
    ],
    materials: [
      {
        id: 'doc-q1-review',
        type: '文档',
        title: 'Q1 产品复盘',
        time: '3 个月前',
        summary: '汇总 Q1 产品目标、核心指标、用户反馈与后续行动。',
        version: 'V1.0',
        status: '已归档',
        sourceState: '来源完整',
      },
      {
        id: 'mail-q1-summary',
        type: '邮件',
        title: 'Q1 复盘结论同步',
        time: '04-02',
        summary: '向项目成员同步复盘结论、历史数据位置和后续责任人。',
      },
    ],
    actionItems: [
      {
        id: 't-q1-archive',
        title: '完成 Q1 复盘资料归档',
        status: '已完成',
        owner: '林薇',
        deadline: '04-02',
        completed: true,
      },
    ],
    graphEdges: [{ from: 'Q1 产品复盘', to: '首次任务成功率', relation: '文档 · 事实（结论）' }],
    pendingMemoryItems: [],
    memoryItems: [
      {
        id: 'memory-q1-onboarding',
        content: '导航改版提升了功能发现率，但首次任务成功率仍低于目标。',
        type: '产品结论',
        status: '已确认',
      },
    ],
    fileItems: [
      {
        id: 'file-q1-metrics',
        name: 'Q1-核心指标.csv',
        extension: 'CSV',
        time: '03-25',
        summary: '包含激活率、首次任务成功率和关键路径流失节点。',
      },
    ],
    nextReverseRecall: '已暂停',
    cloudDoc: {
      workspaceId: 'eda37e89-d0bd-414f-b750-04fb0c00aa43',
      docId: 'SCXk2Lxe7Q',
      title: 'Q1 产品复盘',
    },
  },
];

export const CONTEXT_ROOM_RECOMMENDATIONS: ContextRoomRecommendation[] = [
  {
    id: 'rec-room-pricing',
    name: 'V1 报价与交付',
    kind: '议题',
    reason: '最近 7 天出现 2 封报价邮件、1 次客户会议和 3 个相关任务。',
    dataCount: 6,
    triggered: '今天 10:42',
    confidence: '待确认',
    anchorEntity: {
      name: '张总',
      type: '人物',
      description: '客户对来源追溯和交付范围的要求在最近资料中反复出现。',
    },
    factCount: 12,
    sources: [
      {
        type: '邮件',
        name: '关于 NexOS PC 端报价确认',
        roomId: 'room-launch',
        objectId: 'mail-quote',
      },
      { type: '会议', name: '客户沟通会', roomId: 'room-launch', objectId: 'mtg-client' },
    ],
  },
  {
    id: 'rec-room-design',
    name: 'PC 原型评审',
    kind: '事件',
    reason: '设计稿、评审日程和晨会录音围绕同一交付节点持续更新。',
    dataCount: 4,
    triggered: '昨天',
    confidence: '较高',
    anchorEntity: {
      name: '原型 V2 评审',
      type: '事件',
      description: '设计稿、评审日程和晨会录音正在围绕同一个交付节点收敛。',
    },
    factCount: 8,
    sources: [
      {
        type: '文件',
        name: 'V2-评审稿.fig',
        roomId: 'room-launch',
        objectId: 'file-prototype-review',
      },
      { type: '会议', name: '原型 V2 评审会' },
    ],
  },
];

export const RECENT_ROOM_IDS = ['room-launch', 'room-zhang', 'room-pkm'];
