import type { NormalizedAttachment, NormalizedMailChange, NormalizedMail } from "@nxcore/connector-contract";
function decode(value?:string){ if(!value)return undefined; try{return Buffer.from(value.replace(/-/g,"+").replace(/_/g,"/"),"base64").toString("utf8");}catch{return undefined;} }
export function normalizeGmailMessage(raw:any):NormalizedMailChange {
  const headers = new Map<string,string>((raw.payload?.headers??[]).map((h:any)=>[String(h.name).toLowerCase(),String(h.value)]));
  const labels:string[]=raw.labelIds??[]; let text:string|undefined,html:string|undefined; const attachments:NormalizedAttachment[]=[];
  const walk=(p:any):void=>{if(p.mimeType==="text/plain")text=decode(p.body?.data)??text;if(p.mimeType==="text/html")html=decode(p.body?.data)??html;if(p.body?.attachmentId)attachments.push({providerId:String(p.body.attachmentId),...(p.filename?{filename:String(p.filename)}:{}),...(p.mimeType?{mimeType:String(p.mimeType)}:{}),...(p.body.size!==undefined?{size:Number(p.body.size)}:{})});for(const child of p.parts??[])walk(child);}; walk(raw.payload??{});
  const subject=headers.get("subject");
  const message:NormalizedMail={providerMessageId:String(raw.id),isRead:!labels.includes("UNREAD"),isStarred:labels.includes("STARRED"),isDraft:labels.includes("DRAFT"),memberships:labels,attachments,addresses:[...headers.entries()].filter(([k])=>["from","to","cc","bcc","reply-to"].includes(k)).map(([role,address])=>({role,address})),...(raw.threadId?{providerThreadId:String(raw.threadId)}:{}),...(subject?{subject}:{}),...(raw.snippet?{snippet:String(raw.snippet)}:{}),...(text?{textBody:text}:{}),...(html?{htmlBody:html}:{}),...(raw.internalDate?{receivedAt:new Date(Number(raw.internalDate)).toISOString()}:{}),...(raw.historyId?{providerRevision:String(raw.historyId)}:{})};
  return {kind:"upsert",message};
}
export function gmailHistoryChanges(raw:any):Array<{id:string;removed:boolean}>{ const map=new Map<string,boolean>(); for(const h of raw.history??[]){ for(const x of h.messagesAdded??[])map.set(String(x.message.id),false); for(const x of h.labelsAdded??[])map.set(String(x.message.id),false); for(const x of h.labelsRemoved??[])map.set(String(x.message.id),false); for(const x of h.messagesDeleted??[])map.set(String(x.message.id),true); } return [...map].map(([id,removed])=>({id,removed})); }
